### ISSUE TITLE
Stack traces reference the webpack bundle

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/open-api#57]
```sh
{ TypeError: Cannot read property 'authorization' of undefined
    at checkAuthAndResolve (/home/stuart/open-api/.webpack/service/handler.js:485:33)
    at users (/home/stuart/open-api/.webpack/service/handler.js:660:109)
    # ...
}
```
Not much of a problem whilst I am developing the feature that is throwing errors, but not very helpful for future developers potentially having to cross-ref the bundle to the source manually.

Expected output: 
```sh
{ TypeError: Cannot read property 'authorization' of undefined
    at checkAuthAndResolve (/home/stuart/open-api/graphql/resolvers/checkResolvers.js:10:47)
    at users (/home/stuart/open-api/graphql/typeDefs/User/index.js:5:17)
    # ...
}
```

**Comment by ojongerius** [comment]
#60 will do, not exactly, but close to what you expected, by using source-map-support. This is my  throwing a random error in `dataLayer/mongo/user.js`. The stacktrace now includes now references the right file and line number:

```sh
Serverless: POST /graphql (λ: graphql)
Re-using existing database connection
{ Error: Eek
    at Object.getUsers (/Users/ojongerius/repos/fcc-open-api/.webpack/service/webpack:/dataLayer/mongo/user.js:13:9)
    at users (/Users/ojongerius/repos/fcc-open-api/.webpack/service/webpack:/graphql/resolvers/user.js:5:25)
    at /Users/ojongerius/repos/fcc-open-api/node_modules/graphql-tools/src/schemaGenerator.ts:683:22
    at resolveFieldValueOrError (/Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:531:18)
    at resolveField (/Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:495:16)
    at /Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:361:42)
    at executeOperation (/Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:289:122)
    at executeImpl (/Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:154:14)
    at Object.execute (/Users/ojongerius/repos/fcc-open-api/node_modules/graphql/execution/execute.js:131:229)
    at doRunQuery (/Users/ojongerius/repos/fcc-open-api/node_modules/apollo-server-core/src/runQuery.ts:194:7)
    at /Users/ojongerius/repos/fcc-open-api/node_modules/apollo-server-core/src/runQuery.ts:79:39
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  originalMessage: 'Eek',
  message: 'Error in resolver Query.users\nEek' }
```
